### ISSUE TITLE
"panicked at 'attempt to divide by zero" when I call functions.

### ISSUE THREAD

**Issue by jimmy3dita** [near/initial-contracts#5]
I've sent 500 $NEAR from an account with 500 $NEAR. It succeeded but now I can't anymore interact with the contract.
Deposit TX - https://explorer.betanet.nearprotocol.com/transactions/FjpmJWbdBfWbGctwpJrGQpEViYWGgm7rHKzL64WxXTXp

```
o:nearprotocol pepe$ near call nearkat withdraw '{"amount": "500000000000000000000000000"}' --accountId nuc2.test
Using options: {
  accountId: 'nuc2.test',
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.nearprotocol.com',
  contractName: 'nearkat',
  walletUrl: 'https://wallet.betanet.nearprotocol.com',
  helperUrl: 'https://helper.betanet.nearprotocol.com',
  gas: '100000000000000',
  amount: '0',
  methodName: 'withdraw',
  args: '{"amount": "500000000000000000000000000"}'
}
Scheduling a call: nearkat.withdraw({"amount": "500000000000000000000000000"})
Error:  GuestPanic [Error]: Smart contract panicked: panicked at &#39;attempt to divide by zero&#39;, src&#x2F;lib.rs:103:47
    at Object.parseRpcError (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/utils/rpc_errors.js:25:19)
    at Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/account.js:114:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async scheduleFunctionCall (/usr/local/lib/node_modules/near-shell/commands/call.js:29:34)
    at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) {
  type: 'GuestPanic',
  index: 0,
  panic_msg: "panicked at 'attempt to divide by zero', src/lib.rs:103:47"
}
```

**Comment by evgenykuzyakov** [comment]
Seems the issue is here: https://github.com/near/initial-contracts/blob/62bb406180da3f7082e64c0e0eba5448f0bc0b04/staking-pool/src/lib.rs#L103
